/* eslint-disable */
/* auto-generated by napi-rs / manually maintained for Native* type aliases */

// ─── Shared geometry ─────────────────────────────────────────────────────────

export interface NativeBoundingRect {
  x: number
  y: number
  width: number
  height: number
}

// ─── UIA Element tree ────────────────────────────────────────────────────────

export interface NativeUiElement {
  name: string
  controlType: string
  automationId: string
  className?: string
  isEnabled: boolean
  boundingRect?: NativeBoundingRect | null
  patterns: Array<string>
  depth: number
  value?: string
}

export interface NativeUiElementsResult {
  windowTitle: string
  windowClassName?: string | null
  windowRect?: NativeBoundingRect | null
  elementCount: number
  elements: Array<NativeUiElement>
}

// ─── Scroll ──────────────────────────────────────────────────────────────────

export interface NativeScrollResult {
  ok: boolean
  scrolled: boolean
  error?: string | null
}

export interface NativeScrollAncestor {
  name: string
  automationId: string
  controlType: string
  verticalPercent: number
  horizontalPercent: number
  verticallyScrollable: boolean
  horizontallyScrollable: boolean
}

// ─── Focus / point ───────────────────────────────────────────────────────────

export interface NativeUiaFocusInfo {
  name: string
  controlType: string
  automationId?: string
  value?: string
}

export interface NativeFocusAndPointResult {
  focused?: NativeUiaFocusInfo | null
  atPoint?: NativeUiaFocusInfo | null
}

// ─── Actions ─────────────────────────────────────────────────────────────────

export interface NativeActionResult {
  ok: boolean
  element?: string | null
  error?: string | null
  code?: string | null
}

// ─── Element bounds ──────────────────────────────────────────────────────────

export interface NativeElementBounds {
  name: string
  controlType: string
  automationId: string
  boundingRect?: NativeBoundingRect | null
  value?: string | null
}

// ─── Image processing (Hybrid Non-CDP pipeline) ──────────────────────────────

export interface NativePreprocessOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  scale: number
}

export interface NativeImageProcessingResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

export interface NativeSomLabel {
  id: number
  x: number
  y: number
  width: number
  height: number
}

export interface NativeDrawSomLabelsOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  labels: Array<NativeSomLabel>
}

export interface NativeDrawSomLabelsResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

// ─── Exported functions ──────────────────────────────────────────────────────

export declare function computeChangeFraction(prev: Buffer, curr: Buffer, width: number, height: number, channels: number): number
export declare function dhashFromRaw(raw: Buffer, width: number, height: number, channels: number): bigint
export declare function hammingDistance(a: bigint, b: bigint): number

export declare function uiaGetElements(opts: { windowTitle: string; maxDepth?: number; maxElements?: number; fetchValues?: boolean }): Promise<NativeUiElementsResult>
export declare function uiaGetFocusedAndPoint(opts: { cursorX: number; cursorY: number }): Promise<NativeFocusAndPointResult>
export declare function uiaGetFocusedElement(): Promise<NativeUiaFocusInfo | null>

export declare function uiaClickElement(opts: { windowTitle: string; name?: string; automationId?: string; controlType?: string }): Promise<NativeActionResult>
export declare function uiaSetValue(opts: { windowTitle: string; value: string; name?: string; automationId?: string }): Promise<NativeActionResult>
export declare function uiaInsertText(opts: { windowTitle: string; value: string; name?: string; automationId?: string }): Promise<NativeActionResult>
export declare function uiaGetElementBounds(opts: { windowTitle: string; name?: string; automationId?: string; controlType?: string }): Promise<NativeElementBounds | null>
export declare function uiaGetElementChildren(opts: { windowTitle: string; name?: string; automationId?: string; controlType?: string; maxDepth: number; maxElements: number; timeoutMs: number }): Promise<Array<NativeUiElement>>
export declare function uiaGetTextViaTextPattern(opts: { windowTitle: string; timeoutMs: number }): Promise<string | null>

export declare function uiaScrollIntoView(opts: { windowTitle: string; name?: string; automationId?: string }): Promise<NativeScrollResult>
export declare function uiaGetScrollAncestors(opts: { windowTitle: string; elementName: string }): Promise<Array<NativeScrollAncestor>>
export declare function uiaScrollByPercent(opts: { windowTitle: string; elementName: string; verticalPercent: number; horizontalPercent: number }): Promise<NativeScrollResult>
export declare function uiaGetVirtualDesktopStatus(hwndIntegers: Array<string>): Promise<Record<string, boolean>>

export declare function preprocessImage(opts: NativePreprocessOptions): Promise<NativeImageProcessingResult>
export declare function drawSomLabels(opts: NativeDrawSomLabelsOptions): Promise<NativeDrawSomLabelsResult>
