// Native* type aliases for the napi-rs addon.
// This is the single source of truth — import Native* types from here, not from index.d.ts.
// index.d.ts is auto-generated by napi-rs and does not preserve these aliases.

export interface NativeBoundingRect {
  x: number
  y: number
  width: number
  height: number
}

export interface NativeUiElement {
  name: string
  controlType: string
  automationId: string
  className?: string
  isEnabled: boolean
  boundingRect?: NativeBoundingRect | null
  patterns: Array<string>
  depth: number
  value?: string
}

export interface NativeUiElementsResult {
  windowTitle: string
  windowClassName?: string | null
  windowRect?: NativeBoundingRect | null
  elementCount: number
  elements: Array<NativeUiElement>
}

export interface NativeScrollResult {
  ok: boolean
  scrolled: boolean
  error?: string | null
}

export interface NativeScrollAncestor {
  name: string
  automationId: string
  controlType: string
  verticalPercent: number
  horizontalPercent: number
  verticallyScrollable: boolean
  horizontallyScrollable: boolean
}

export interface NativeUiaFocusInfo {
  name: string
  controlType: string
  automationId?: string
  value?: string
}

export interface NativeFocusAndPointResult {
  focused?: NativeUiaFocusInfo | null
  atPoint?: NativeUiaFocusInfo | null
}

export interface NativeActionResult {
  ok: boolean
  element?: string | null
  error?: string | null
  code?: string | null
}

export interface NativeElementBounds {
  name: string
  controlType: string
  automationId: string
  boundingRect?: NativeBoundingRect | null
  value?: string | null
}

export interface NativePreprocessOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  /** Upscale factor: 1, 2, 3, or 4. Values above 4 are rejected by the Rust layer. */
  scale: number
  /** When true, apply Sauvola adaptive binarization after contrast stretch (output: 0/255 only). */
  adaptive?: boolean
}

export interface NativeImageProcessingResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

export interface NativeSomLabel {
  id: number
  x: number
  y: number
  width: number
  height: number
}

export interface NativeDrawSomLabelsOptions {
  data: Buffer
  width: number
  height: number
  channels: number
  labels: Array<NativeSomLabel>
}

export interface NativeDrawSomLabelsResult {
  data: Buffer
  width: number
  height: number
  channels: number
}

// ── Win32 hot-path bindings (ADR-007 P1) ─────────────────────────────────────

/** Rust `RECT` mirror — left/top/right/bottom in screen pixels. The TS wrapper
 *  in `src/engine/win32.ts` converts to `{ x, y, width, height }` for callers. */
export interface NativeWin32Rect {
  left: number
  top: number
  right: number
  bottom: number
}

/** Combined return for `GetWindowThreadProcessId`. The Win32 API's out-pointer
 *  + return value are folded into one struct so the TS wrapper just reads
 *  `.threadId` / `.processId`. */
export interface NativeThreadProcessId {
  threadId: number
  processId: number
}

// ── Win32 GDI / monitor / DPI (ADR-007 P2) ───────────────────────────────────

/** Result of `win32PrintWindowToBuffer`: RGBA top-down pixels (length = w*h*4). */
export interface NativePrintWindowResult {
  data: Buffer
  width: number
  height: number
}

/** One monitor as returned by `win32EnumMonitors`. The TS wrapper rebuilds
 *  the nested `{ bounds, workArea }` shape that callers (`MonitorInfo`)
 *  expect — this flat record matches the napi marshal layout. */
export interface NativeMonitorInfo {
  handle: bigint
  primary: boolean
  boundsLeft: number
  boundsTop: number
  boundsRight: number
  boundsBottom: number
  workLeft: number
  workTop: number
  workRight: number
  workBottom: number
  dpi: number
}

// ── Win32 process / input (ADR-007 P3) ───────────────────────────────────────

/** Outcome of `win32ForceSetForegroundWindow`. The TS wrapper repacks
 *  these into snake_case (`fg_before` / `fg_after`) for legacy public API
 *  compatibility (Tool Surface 不変原則 P7). */
export interface NativeForceFocusResult {
  ok: boolean
  attached: boolean
  fgBefore: bigint
  fgAfter: bigint
}

/** One Toolhelp32 row. The TS wrapper builds a Map<number, number>. */
export interface NativeProcessParentEntry {
  pid: number
  parentPid: number
}

/** Process identity result. Partial success is allowed: a missing
 *  process_name leaves it as "" and a missing creation time leaves
 *  process_start_time_ms = 0. */
export interface NativeProcessIdentity {
  pid: number
  processName: string
  processStartTimeMs: number
}

/** Scrollbar position snapshot. `pageRatio` (0..1) is precomputed. */
export interface NativeScrollInfo {
  nMin: number
  nMax: number
  nPage: number
  nPos: number
  pageRatio: number
}

// ── Desktop Duplication (Phase 3) ────────────────────────────────────────────

export interface NativeDirtyRect {
  x: number
  y: number
  width: number
  height: number
}

export interface NativeOutputBounds {
  x: number
  y: number
  width: number
  height: number
}

// ── Visual GPU Phase 4 (ADR-005) ─────────────────────────────────────────────

/** Rust src/vision_backend/types.rs::Rect */
export interface NativeVisionRect {
  x: number
  y: number
  width: number
  height: number
}

/** Rust src/vision_backend/types.rs::RoiInput */
export interface NativeRoiInput {
  trackId: string
  rect: NativeVisionRect
  classHint?: string | null
}

/** Rust src/vision_backend/types.rs::RecognizeRequest */
export interface NativeRecognizeRequest {
  targetKey: string
  /** Session key from `init_session_blocking`. Empty string → legacy dummy path. */
  sessionKey: string
  rois: NativeRoiInput[]
  frameWidth: number
  frameHeight: number
  /** Captured frame RGBA bytes, length = frameWidth * frameHeight * 4.
   *  Empty Buffer → legacy dummy path (no preprocess, stub candidates). */
  frameBuffer: Buffer
  nowMs: number
}

/** Rust src/vision_backend/types.rs::RawCandidate */
export interface NativeRawCandidate {
  trackId: string
  rect: NativeVisionRect
  /** Empty string when class is "icon" or detection found a non-text element. */
  label: string
  /** "text"|"icon"|"mixed"|"button"|"checkbox"|"radio"|"dropdown"|"slider"|"tab"|"label"|"image"|"title"|"other" */
  class: string
  confidence: number
  provisional: boolean
}

/**
 * Rust src/vision_backend/capability.rs::CapabilityProfile
 *
 * Sample for the dogfood machine (RX 9070 XT, Win11 24H2):
 *   { os: "windows", osBuild: 26100, gpuVendor: "AMD", gpuArch: "RDNA4", winml: true, directml: true, ... }
 */
export interface NativeCapabilityProfile {
  os: string
  osBuild: number
  gpuVendor: string
  gpuDevice: string
  gpuArch: string
  gpuVramMb: number
  winml: boolean
  directml: boolean
  rocm: boolean
  cuda: boolean
  tensorrt: boolean
  cpuIsa: string[]
  backendBuilt: boolean
  epsBuilt: string[]
}

// ── Phase 4b-1: EP cascade session init ──────────────────────────────────────

/**
 * Rust src/vision_backend/types.rs::NativeSessionInit
 *
 * Input to `visionInitSession`. `profile` should be obtained from
 * `detectCapability()` so the cascade can select the optimal EP.
 */
export interface NativeSessionInit {
  /** Absolute path to the .onnx file to load. */
  modelPath: string
  /** CapabilityProfile produced by detectCapability(). */
  profile: NativeCapabilityProfile
  /**
   * Optional stable session key for later pool lookup (e.g. "ui_detector:dml-fp16").
   * Pass an empty string for ad-hoc sessions.
   */
  sessionKey: string
}

/**
 * Rust src/vision_backend/types.rs::NativeSessionResult
 *
 * Returned by `visionInitSession`. The Promise **never rejects** — errors are
 * reported via `ok === false` to maintain L5 process isolation.
 */
export interface NativeSessionResult {
  ok: boolean
  /**
   * Set when `ok === true`. Format: "WinML" | "DirectML(0)" | "ROCm(0)" |
   * "CUDA(0)" | "CPU" | "Fallback(reason)"
   */
  selectedEp: string
  /** Set when `ok === false`. Concatenated cascade attempt errors. */
  error?: string | null
  /** Echoed `sessionKey` — use as lookup key for subsequent recognize_rois calls (4b-4+). */
  sessionKey: string
}

// ── ADR-007 P5a: L1 capture ring buffer ──────────────────────────────────────

/** napi 公開する EventEnvelope の TS 側表現。Rust 内部の InternalEvent は
 *  payload を Vec<u8> で所有するが、JS 側では Buffer (fresh allocation) として渡る。 */
export interface NativeEventEnvelope {
  envelopeVersion: number
  eventId: bigint
  wallclockMs: bigint
  subOrdinal: number
  timestampSource: number
  kind: number
  payloadBytes: Buffer
  sessionId?: string | null
  toolCallId?: string | null
}

/** L1 ring buffer のヘルスチェック結果。bench / server_status 用。 */
export interface NativeCaptureStats {
  uptimeMs: bigint
  pushCount: bigint
  dropCount: bigint
  currentBuffered: number
  panicCount: bigint
  eventIdHighWater: bigint
}
