/**
 * internal #252 — the stub catalog IS the Windows server's `tools/list`, byte for byte.
 *
 * The non-Windows stub (`server-linux-stub.ts`) serves `STUB_TOOL_CATALOG` so directory hosts can
 * read the real tool surface. That catalog used to be produced by parsing the tool modules' source
 * text, which lost or substituted whatever it could not read — a describe with a trailing comma,
 * an object default, every field behind a `...spread`, whole schemas of named union variants,
 * `required`, `exclusiveMinimum`, array `items` — and `check:stub-catalog` compared the catalog only
 * with its own regeneration, so every loss was committed green (gate 2 on #792, two rounds).
 *
 * Now there is nothing to parse. This file registers the same tools the server registers
 * (`CATALOG_TOOL_REGISTRARS`, then the key locker, in the server's order) on a real `McpServer`,
 * reads `tools/list` through the SDK's own client, and:
 *   - with `DESKTOP_TOUCH_WRITE_STUB_CATALOG=1` (set only by `npm run generate:stub-catalog`),
 *     writes the catalog from it;
 *   - otherwise requires the committed catalog to be exactly what it would write.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { CATALOG_TOOL_REGISTRARS } from "../../src/tools/catalog-registrars.js";
import { registerKeyLockerTools } from "../../src/tools/key-locker-tool.js";
import { captureAdviceConfiguration } from "../../src/tools/_advice-capability.js";

const CATALOG_PATH = fileURLToPath(new URL("../../src/stub-tool-catalog.ts", import.meta.url));
const SERVER_PATH = fileURLToPath(new URL("../../src/server-windows.ts", import.meta.url));

const HEADER = `/**
 * Auto-generated by \`npm run generate:stub-catalog\` — do not edit.
 *
 * This is the Windows server's \`tools/list\` (default configuration: v2 tools and the key locker
 * enabled), captured by registering the real tools on a real McpServer
 * (tests/unit/stub-catalog-is-the-live-tools-list.test.ts). It is native-free: the non-Windows
 * stub imports it so directory hosts such as Glama can inspect the real tool descriptions and
 * argument schema without loading Win32, UIA, CDP, nut-js, or any Windows native addon.
 */

export type JsonSchemaObject = {
  type: "object";
  properties?: Record<string, unknown>;
  required?: string[];
  additionalProperties?: boolean;
  [keyword: string]: unknown;
};

export interface StubToolCatalogEntry {
  name: string;
  description: string;
  inputSchema: JsonSchemaObject;
}

`;

async function liveCatalogSource(): Promise<{ source: string; names: string[] }> {
  // The default configuration, as the server would hold it: the kill switches off.
  const saved = {
    v2: process.env.DESKTOP_TOUCH_DISABLE_FUKUWARAI_V2,
    locker: process.env.DESKTOP_TOUCH_DISABLE_KEY_LOCKER,
  };
  delete process.env.DESKTOP_TOUCH_DISABLE_FUKUWARAI_V2;
  delete process.env.DESKTOP_TOUCH_DISABLE_KEY_LOCKER;
  try {
    const server = new McpServer({ name: "stub-catalog", version: "0" });
    for (const register of CATALOG_TOOL_REGISTRARS) register(server);
    captureAdviceConfiguration({ v2: true, credentialStore: true });
    registerKeyLockerTools(server);
    const [serverSide, clientSide] = InMemoryTransport.createLinkedPair();
    const client = new Client({ name: "stub-catalog", version: "0" });
    await Promise.all([server.connect(serverSide), client.connect(clientSide)]);
    const { tools } = await client.listTools();
    await client.close();
    const entries = tools
      .map((t) => ({ name: t.name, description: t.description ?? "", inputSchema: t.inputSchema }))
      .sort((a, b) => a.name.localeCompare(b.name));
    const source =
      HEADER +
      `export const STUB_TOOL_CATALOG: StubToolCatalogEntry[] = ${JSON.stringify(entries, null, 2)};\n\n` +
      `export const STUB_TOOL_COUNT = STUB_TOOL_CATALOG.length;\n`;
    return { source, names: entries.map((e) => e.name) };
  } finally {
    if (saved.v2 !== undefined) process.env.DESKTOP_TOUCH_DISABLE_FUKUWARAI_V2 = saved.v2;
    if (saved.locker !== undefined) process.env.DESKTOP_TOUCH_DISABLE_KEY_LOCKER = saved.locker;
  }
}

describe("the stub catalog", () => {
  it("is exactly what the server's tools/list answers", async () => {
    const { source, names } = await liveCatalogSource();
    // CONTROLS: the live side really registered the surface — 30 stub tools, the key locker among
    // them — so "equal" is not two near-empty files agreeing.
    expect(names.length).toBeGreaterThanOrEqual(30);
    expect(names).toContain("key_locker");
    if (process.env.DESKTOP_TOUCH_WRITE_STUB_CATALOG === "1") {
      writeFileSync(CATALOG_PATH, source, "utf8");
      return;
    }
    const committed = readFileSync(CATALOG_PATH, "utf8").replace(/\r\n/g, "\n");
    expect(committed, "src/stub-tool-catalog.ts is stale — run `npm run generate:stub-catalog`").toBe(source);
  });

  it("covers every tool the server registers outside the v2 module", () => {
    // The list is shared with the server; this is what notices a tool registered BESIDE it. Every
    // `register…(s)` call in the server is either the shared list or one named here with why.
    const server = readFileSync(SERVER_PATH, "utf8");
    const calls = [...server.matchAll(/^\s*(?:_desktopV2\.)?(register[A-Z]\w*)\(s\);/gm)].map((m) => m[1]);
    const ACCOUNTED: Record<string, string> = {
      registerKeyLockerTools: "registered by this file after the list, as the server does",
      registerScreenshotResources: "resources, no tools",
      registerPerceptionResources: "resources, no tools",
      registerDesktopTools: "desktop_discover / desktop_act — the dynamic v2 pair, not in the stub catalog",
    };
    // CONTROL: the scan finds the calls it accounts for, so an empty match is not a pass.
    expect(calls).toContain("registerKeyLockerTools");
    expect(calls.filter((c) => !(c in ACCOUNTED))).toEqual([]);
    expect(server).toMatch(/for \(const register of CATALOG_TOOL_REGISTRARS\) register\(s\);/);
  });
});
