/**
 * internal #252 — the stub catalog is the Windows server's `tools/list` for its catalog surface,
 * byte for byte.
 *
 * The non-Windows stub (`server-linux-stub.ts`) serves `STUB_TOOL_CATALOG` so directory hosts can
 * read the real tool surface. That catalog used to be produced by parsing the tool modules' source
 * text, which lost or substituted whatever it could not read — a describe with a trailing comma,
 * an object default, every field behind a `...spread`, whole schemas of named union variants,
 * `required`, `exclusiveMinimum`, array `items` — and `check:stub-catalog` compared the catalog only
 * with its own regeneration, so every loss was committed green (gate 2 on #792, two rounds).
 *
 * Now there is nothing to parse. This file takes the server's three registration steps — the shared
 * list (`CATALOG_TOOL_REGISTRARS`), the advice configuration, the key locker — on a real `McpServer`
 * in the default configuration, reads `tools/list` through the SDK's own client, and:
 *   - with `DESKTOP_TOUCH_WRITE_STUB_CATALOG=1` (set only by `npm run generate:stub-catalog`),
 *     writes the catalog from it;
 *   - otherwise requires the committed catalog to be exactly what it would write.
 *
 * The catalog surface is every tool except the two the v2 module registers dynamically
 * (`desktop_discover`, `desktop_act`): 30 stub + 2 dynamic.
 */
import { describe, expect, it } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { KILL_SWITCHES } from "../../scripts/lib/stub-catalog-env.mjs";

const CATALOG_PATH = fileURLToPath(new URL("../../src/stub-tool-catalog.ts", import.meta.url));
const SERVER_PATH = fileURLToPath(new URL("../../src/server-windows.ts", import.meta.url));

// The kill switches that change what registers, or what a description says. Some are read when a
// module is IMPORTED (`macro.ts` decides which step tools `run_macro` names at module init), so
// they are cleared before the tool modules are imported — below, by dynamic import — not after
// (gate 2 round 3 and Codex on #792: clearing them after a static import wrote a catalog naming
// the V1 tools, under a header saying v2 was enabled).
for (const name of KILL_SWITCHES as string[]) delete process.env[name];

const HEADER = `/**
 * Auto-generated by \`npm run generate:stub-catalog\` — do not edit.
 *
 * The Windows server's \`tools/list\` for its catalog surface — every tool but the two the v2
 * module registers dynamically (desktop_discover, desktop_act) — in the default configuration
 * (v2 tools and the key locker enabled), captured by registering the real tools on a real
 * McpServer (tests/unit/stub-catalog-is-the-live-tools-list.test.ts). It is native-free: the
 * non-Windows stub imports it so directory hosts such as Glama can inspect the real tool
 * descriptions and argument schema without loading Win32, UIA, CDP, nut-js, or any Windows
 * native addon.
 */

export type JsonSchemaObject = {
  type: "object";
  properties?: Record<string, unknown>;
  required?: string[];
  additionalProperties?: boolean;
  [keyword: string]: unknown;
};

export interface StubToolCatalogEntry {
  name: string;
  description: string;
  inputSchema: JsonSchemaObject;
}

`;

async function liveCatalogSource(): Promise<{ source: string; names: string[] }> {
  const { McpServer } = await import("@modelcontextprotocol/sdk/server/mcp.js");
  const { CATALOG_TOOL_REGISTRARS } = await import("../../src/tools/catalog-registrars.js");
  const { captureAdviceConfiguration } = await import("../../src/tools/_advice-capability.js");
  const { registerKeyLockerTools } = await import("../../src/tools/key-locker-tool.js");
  const server = new McpServer({ name: "stub-catalog", version: "0" });
  // The server's three steps, in its order (the second cell below checks that order there).
  for (const register of CATALOG_TOOL_REGISTRARS) register(server);
  captureAdviceConfiguration({ v2: true, credentialStore: true });
  registerKeyLockerTools(server);
  const [serverSide, clientSide] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "stub-catalog", version: "0" });
  await Promise.all([server.connect(serverSide), client.connect(clientSide)]);
  const { tools } = await client.listTools();
  await client.close();
  const entries = tools
    .map((t) => ({ name: t.name, description: t.description ?? "", inputSchema: t.inputSchema }))
    .sort((a, b) => a.name.localeCompare(b.name));
  const source =
    HEADER +
    `export const STUB_TOOL_CATALOG: StubToolCatalogEntry[] = ${JSON.stringify(entries, null, 2)};\n\n` +
    `export const STUB_TOOL_COUNT = STUB_TOOL_CATALOG.length;\n`;
  return { source, names: entries.map((e) => e.name) };
}

describe("the stub catalog", () => {
  it("is exactly what the server's tools/list answers for its catalog surface", async () => {
    const { source, names } = await liveCatalogSource();
    // CONTROLS: the live side really registered the surface — 30 stub tools, the key locker among
    // them, and run_macro naming the v2 pair — so "equal" is not two near-empty files agreeing.
    expect(names.length).toBeGreaterThanOrEqual(30);
    expect(names).toContain("key_locker");
    expect(source).toContain("desktop_discover");
    if (process.env.DESKTOP_TOUCH_WRITE_STUB_CATALOG === "1") {
      writeFileSync(CATALOG_PATH, source, "utf8");
      return;
    }
    const committed = readFileSync(CATALOG_PATH, "utf8").replace(/\r\n/g, "\n");
    expect(committed, "src/stub-tool-catalog.ts is stale — run `npm run generate:stub-catalog`").toBe(source);
  });

  it("covers every tool the server registers outside the v2 module", () => {
    // The list is shared with the server; this is what notices a tool registered BESIDE it, and a
    // change to the order this file repeats. The server cannot be imported here (top-level awaits on native modules), so its
    // source is read — every form a registration takes, not one spelling of it (gate 2 round 3:
    // a direct s.tool / s.registerTool, a register call with a second argument, and one inside an
    // `if` all passed a scan for `registerX(s);`).
    const code = readFileSync(SERVER_PATH, "utf8")
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/\/\/[^\n]*/g, "");
    const registerCalls = [...code.matchAll(/\b(register[A-Z]\w*)\s*\(/g)].map((m) => m[1]!);
    const directRegistrations = [...code.matchAll(/\b\w+\s*\.\s*(?:tool|registerTool)\s*\(/g)].length;
    const ACCOUNTED: Record<string, string> = {
      registerKeyLockerTools: "the key locker — this file registers it after the list and the capture",
      registerKeyLockerWiring: "the key locker's autofill wiring, no tools",
      registerScreenshotResources: "resources, no tools",
      registerPerceptionResources: "resources, no tools",
      registerDesktopTools: "desktop_discover / desktop_act — the dynamic v2 pair, not in the stub catalog",
    };
    // The three steps, once each and in this order — the order this file repeats. (The capture
    // cannot move into a shared function: the presenter's cell allows it only here.)
    const LOOP = "for (const register of CATALOG_TOOL_REGISTRARS) register(s);";
    const at = [LOOP, "captureAdviceConfiguration(", "registerKeyLockerTools(s);"].map((needle) => {
      expect(code.split(needle).length - 1, `${needle} once in server-windows.ts`).toBe(1);
      return code.indexOf(needle);
    });
    expect(at, "the list, then the capture, then the key locker").toEqual([...at].sort((x, y) => x - y));
    expect(registerCalls.filter((c) => !(c in ACCOUNTED))).toEqual([]);
    // The three V1 fallbacks (get_windows, get_ui_elements, set_element_value), registered with
    // s.tool only when v2 is disabled — not the default surface. A fourth is a tool beside the list.
    expect(directRegistrations, "a tool registered directly in server-windows.ts, beside registerCatalogTools").toBe(3);
  });
});
