/**
 * The tools every Windows server registers, in the order it registers them.
 *
 * `server-windows.ts` registers through this list, and the stub catalog (`stub-tool-catalog.ts`)
 * is generated by registering the same list on a real `McpServer` and writing what `tools/list`
 * answers (`tests/unit/stub-catalog-is-the-live-tools-list.test.ts`). One list for both, so a tool
 * added here reaches the catalog, and a tool registered anywhere else is caught by that file.
 *
 * Not here, on purpose:
 * - `registerKeyLockerTools` — the server captures the advice configuration between this list and
 *   it; the generator registers it after this list the same way.
 * - `desktop_discover` / `desktop_act` — registered dynamically by the v2 module, and not part of
 *   the stub catalog (30 stub + 2 dynamic).
 * - resources (`registerScreenshotResources`, `registerPerceptionResources`) and the key locker's
 *   wiring, which register no tools.
 *
 * internal #252 (gate 2 on #792): the catalog used to be produced by parsing these modules' source
 * text, which lost or substituted whatever it could not read and committed the result green.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerScreenshotTools } from "./screenshot.js";
import { registerMouseTools } from "./mouse.js";
import { registerKeyboardTools } from "./keyboard.js";
import { registerWindowTools } from "./window.js";
import { registerUiElementTools } from "./ui-elements.js";
import { registerWorkspaceTools } from "./workspace.js";
import { registerMacroTools } from "./macro.js";
import { registerScrollTools } from "./scroll.js";
import { registerBrowserTools } from "./browser.js";
import { registerWindowDockTools } from "./window-dock.js";
import { registerWaitUntilTool } from "./wait-until.js";
import { registerDesktopStateTools } from "./desktop-state.js";
import { registerTerminalTools } from "./terminal.js";
import { registerEventTools } from "./events.js";
import { registerClipboardTools } from "./clipboard.js";
import { registerNotificationTools } from "./notification.js";
import { registerExcelTools } from "./excel.js";
import { registerPerceptionTools } from "./perception.js";
import { registerServerStatusTool } from "./server-status.js";
import { registerScreenshotQueryTool } from "./screenshot-query.js";
import { registerScreenshotGcTool } from "./screenshot-gc.js";

export const CATALOG_TOOL_REGISTRARS: ReadonlyArray<(server: McpServer) => void> = [
  registerScreenshotTools,
  registerMouseTools,
  registerKeyboardTools,
  registerWindowTools,
  registerUiElementTools,
  registerWorkspaceTools,
  registerMacroTools,
  registerScrollTools,
  registerBrowserTools,
  registerWindowDockTools,
  registerWaitUntilTool,
  registerDesktopStateTools,
  registerTerminalTools,
  registerEventTools,
  registerClipboardTools,
  registerNotificationTools,
  registerExcelTools,
  registerPerceptionTools,
  registerServerStatusTool,
  // ADR-026 Phase 3 — screenshot disk-cache observe (query) + reclaim (gc).
  registerScreenshotQueryTool,
  registerScreenshotGcTool,
];
